"""auto_update_1779898460

Revision ID: 83cf62b5cda6
Revises: c2d4e6f8a0b1
Create Date: 2026-05-28 00:14:20.251615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83cf62b5cda6'
down_revision = 'c2d4e6f8a0b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
